name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9.0"
      - name: Build
        run: swift build
      # - name: Run tests
      #   run: swift test

